name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/keystore.jks

      - name: Create signing.properties
        run: |
          cat > app/signing.properties << EOF
          storeFile=keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-apks
          path: ./apks

      - name: Prepare release assets
        run: |
          cat <<EOF > release.txt
            # $(date +"%Y-%m-%d %H:%M") compile result
            contains：
            - app-debug.apk
            - app-release.apk
          EOF

      - name: Display structure of downloaded files
        run: ls -R ./apks

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
            name: Release ${{ github.ref_name }}
            tag_name: ${{ github.ref_name }}
            body_path: coremark/release.txt
            files: |
              ./apks/app-debug.apk
              ./apks/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
